# Inspired by https://github.com/maxexcloo/Docker/blob/master/applications/phppgadmin/Dockerfile

FROM maxexcloo/phppgadmin
RUN echo "\$conf['extra_login_security'] = false;" >> /data/http/conf/config.inc.php
